# Site settings
title: "Paulo Bomfim resume"
description: "A resume for Paulo H."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Paulo H Bomfim O"
resume_title:                   "Software Engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "paulobommfim@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+55 71 9 9963 2241"
resume_contact_address:         "Salvador, Brazil"

resume_header_contact_info:     "Salvador, Brazil • +55 71 9 9963 2241 • paulobommfim@gmail.com"
display_header_contact_info:    "true"

resume_header_intro: "<p>Developing applications since 2017</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/phbomfim/"
  resume_twitter_url:           "http://twitter.com/phbomfimdev"
  resume_dribbble_url:          ""
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/phbomfim/"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://phbomfim.netlify.com"
  resume_medium_url:            ""
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
